In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv("pn1.csv")

C:\Users\komsu\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (7) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


In [3]:
data.head()

test_date  cough  fever  sore_throat  shortness_of_breath  head_ache  \
0  2020-11-12      0      0            0                    0          0   
1  2020-11-12      0      1            0                    0          0   
2  2020-11-12      0      0            0                    0          0   
3  2020-11-12      0      0            0                    0          0   
4  2020-11-12      0      1            0                    0          0   

  corona_result age_60_and_above  gender         test_indication  
0      negative               No    male                   Other  
1      negative               No    male                   Other  
2      negative              Yes  female                   Other  
3      negative               No    male                   Other  
4      negative               No    male  Contact with confirmed

In [4]:
data.shape

(2742596, 10)

In [5]:
data.isnull().sum()

test_date                   0
cough                       0
fever                       0
sore_throat                 0
shortness_of_breath         0
head_ache                   0
corona_result               0
age_60_and_above       547644
gender                  92886
test_indication             0
dtype: int64

In [6]:
data.age_60_and_above=data['age_60_and_above'].fillna("don't know")

In [7]:
data.gender=data.gender.fillna("others")

In [8]:
data.isnull().sum()

test_date              0
cough                  0
fever                  0
sore_throat            0
shortness_of_breath    0
head_ache              0
corona_result          0
age_60_and_above       0
gender                 0
test_indication        0
dtype: int64

In [9]:
p=pd.get_dummies(data.age_60_and_above,drop_first=True)

In [10]:
p.head()

Yes  don't know
0    0           0
1    0           0
2    1           0
3    0           0
4    0           0

In [11]:
q=pd.get_dummies(data.gender,drop_first=True)

In [12]:
q.head()

male  others
0     1       0
1     1       0
2     0       0
3     1       0
4     1       0

In [13]:
r=pd.get_dummies(data.test_indication,drop_first=True)

In [14]:
r.head()

Contact with confirmed  Other
0                       0      1
1                       0      1
2                       0      1
3                       0      1
4                       1      0

In [15]:
data.columns

Index(['test_date', 'cough', 'fever', 'sore_throat', 'shortness_of_breath',
       'head_ache', 'corona_result', 'age_60_and_above', 'gender',
       'test_indication'],
      dtype='object')

In [16]:
data=data.drop(['test_date','age_60_and_above','gender','test_indication'],axis=1)

In [17]:
data.columns

Index(['cough', 'fever', 'sore_throat', 'shortness_of_breath', 'head_ache',
       'corona_result'],
      dtype='object')

In [18]:
data=pd.concat([data,p,q,r],axis=1)

In [19]:
data.columns

Index(['cough', 'fever', 'sore_throat', 'shortness_of_breath', 'head_ache',
       'corona_result', 'Yes', 'don't know', 'male', 'others',
       'Contact with confirmed', 'Other'],
      dtype='object')

In [20]:
q.head()

male  others
0     1       0
1     1       0
2     0       0
3     1       0
4     1       0

In [21]:
Y=data.iloc[:,5:6]

In [22]:
Y.head()

corona_result
0      negative
1      negative
2      negative
3      negative
4      negative

In [23]:
data=data.drop(['corona_result'],axis=1)

In [24]:
data.shape

(2742596, 11)

In [25]:
data.isnull().sum()

cough                     0
fever                     0
sore_throat               0
shortness_of_breath       0
head_ache                 0
Yes                       0
don't know                0
male                      0
others                    0
Contact with confirmed    0
Other                     0
dtype: int64

In [26]:
X=data

In [27]:
X.shape

(2742596, 11)

In [28]:
X.dtypes

cough                     int64
fever                     int64
sore_throat               int64
shortness_of_breath       int64
head_ache                 int64
Yes                       uint8
don't know                uint8
male                      uint8
others                    uint8
Contact with confirmed    uint8
Other                     uint8
dtype: object

In [29]:
X=X.values

In [30]:
X[0]

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1], dtype=int64)

In [31]:
X[0]

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1], dtype=int64)

In [32]:
Y=Y.values

In [33]:
Y

array([['negative'],
       ['negative'],
       ['negative'],
       ...,
       ['other'],
       ['negative'],
       ['negative']], dtype=object)

In [34]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.30)

In [35]:
from sklearn.naive_bayes import GaussianNB
model1=GaussianNB()

In [36]:
model1.fit(X_train,y_train)

C:\Users\komsu\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


GaussianNB()

In [37]:
data.dtypes

cough                     int64
fever                     int64
sore_throat               int64
shortness_of_breath       int64
head_ache                 int64
Yes                       uint8
don't know                uint8
male                      uint8
others                    uint8
Contact with confirmed    uint8
Other                     uint8
dtype: object

In [38]:
model1.predict_proba(np.array([[0,0,0,0,0,0,0,0,0,1,0]]))[0][2]*100

98.96706271912656

In [39]:
model1.predict(np.array([[0,0, 0, 0, 0, 0, 0, 0, 0,0,0]]))

array(['positive'], dtype='<U8')

In [40]:
X_train

array([[0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1],
       ...,
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1]], dtype=int64)

In [41]:
pred=model1.predict(X_test)
from sklearn.metrics import accuracy_score
accuracy_score(pred,y_test)

0.9060027054652586

In [42]:
import joblib
joblib.dump(model1,"symptoms_model.sav")

['symptoms_model.sav']

In [43]:
model2 = joblib.load("symptoms_model.sav")

In [44]:
model2.predict(np.array([[0,0, 0, 0, 0, 0, 0, 0, 0,0,0]]))[0]

'positive'

In [45]:
model2.predict_proba(np.array([[0,0, 0, 0, 0, 0, 0, 0, 0,0,0]]))[0][2]

0.5873282562287165

In [46]:
model2.predict(np.array([[1,1 ,1, 1, 1, 0, 0, 0, 0,0,0]]))

array(['positive'], dtype='<U8')

In [47]:
model2.predict_proba(np.array([[0,0 ,0, 0, 0, 0, 0, 0, 0,1,0]]))[0][2]*100

98.96706271912656

In [57]:
val=np.array([[0,0 ,0, 0, 0, 0, 0, 0, 0,1,0]])

In [58]:
model2.predict(val)[0][2]*100

array(['positive'], dtype='<U8')

In [56]:
print(val)

[0 0 0 0 0 0 0 0 0 1 0]
